import Head from 'next/head'
import './globals.css'
import { Inter } from 'next/font/google'
import { Loading } from '@/components/smallComponents/Loading'
import AuthCtx from '@/context/AuthCtx'
import Footer from '../components/Footer'
import NewCartCtx from '@/context/NewCartCtx'
import PrductWrapper from '@/context/ProductContext'
import UserCtx from '@/context/UserCtx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'new shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <Head>
        <title>دمو شاپ</title>
        <meta name='description' content='مدیریت حساب کاربری : ایجاد و ویرایش ادرس و مشخصات فردی' />
      </Head>
      <AuthCtx>
        <UserCtx>
          <NewCartCtx>
            <PrductWrapper>
              {/* <GlobalContext> */}
                {/* <CartCtx> */}
                  <Loading/>
                    {children}
                  <Footer/>
                {/* </CartCtx> */}
              {/* </GlobalContext> */}
            </PrductWrapper>
          </NewCartCtx>
        </UserCtx>
    </AuthCtx>

      </body>
    </html>
  )
}
